# modules/wsl.sh - WSL-specific configuration

MODULE_NAME="wsl"
MODULE_DESCRIPTION="Windows Subsystem for Linux configuration"

# Helper to detect WSL
is_wsl() {
    grep -qiE "(microsoft|wsl)" /proc/version 2>/dev/null
}

module_check() {
    # Only relevant on WSL
    is_wsl || return 1
    # Check if wsl.conf exists with our settings
    [[ -f /etc/wsl.conf ]] && grep -q "systemd=true" /etc/wsl.conf
}

module_install() {
    if ! is_wsl; then
        info "Not running in WSL, skipping"
        return 0
    fi

    info "Configuring WSL..."

    # Get current username
    local current_user="${USER:-$(whoami)}"

    # Optionally add reminder to check for old WSL distros
    read -rp "Set 30-day reminder to delete old WSL distro? [y/N] " set_reminder
    if [[ "$set_reminder" =~ ^[Yy]$ ]]; then
        local remind_until=$(($(date +%s) + 2592000))  # 30 days in seconds
        local remind_date=$(date -d "@$remind_until" +%Y-%m-%d)
        mkdir -p "$HOME/.config"
        echo "$remind_until" > "$HOME/.config/wsl-migration-reminder"
        info "Set reminder to delete old WSL distro after $remind_date"
    fi

    # Create wsl.conf
    sudo tee /etc/wsl.conf > /dev/null <<EOF
# WSL Configuration - Generated by kdub.settings

[boot]
# Enable systemd (required for Docker, services, etc.)
systemd=true

[user]
# Default user when launching WSL
default=$current_user

[interop]
# Don't append Windows PATH to Linux PATH
# Keeps shell startup fast and environment clean
# Add specific Windows tools via modules (e.g., vscode)
appendWindowsPath=false

[network]
# Don't overwrite /etc/hosts on each start
# Allows custom host entries to persist
generateHosts=false
EOF

    info "Created /etc/wsl.conf"
    warn "You must restart WSL for changes to take effect:"
    warn "  wsl --shutdown (from PowerShell)"
}

module_update() {
    module_install
}

module_uninstall() {
    if [[ -f /etc/wsl.conf ]]; then
        sudo rm /etc/wsl.conf
        info "Removed /etc/wsl.conf"
    fi
}

module_config() {
    if is_wsl && [[ ! -f /etc/hosts.custom ]]; then
        # Backup current hosts if it has custom entries
        if grep -qv "localhost\|localdomain\|ip6-" /etc/hosts 2>/dev/null; then
            info "Tip: You have custom entries in /etc/hosts"
            info "These will persist since generateHosts=false"
        fi
    fi
}

module_aliases() { :; }
module_functions() { :; }
module_env() { :; }
module_paths() { :; }
