"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true
console_title_template = "{{ .Folder }}"
accent_color = "#ffffff"
async = true

[transient_prompt]
background = "transparent"
foreground = "gray"
foreground_templates = [ "{{ if gt .Code 0 }}red{{ end }}" ]
template = "❯ "

[[blocks]]
type = "prompt"
alignment = "left"
newline = false

  [[blocks.segments]]
  type = "text"
  style = "plain"
  template = "╭─"
  foreground = "gray"

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "blue"

    [blocks.segments.options]
    style = "full"
    template = ":<b>{{ .Path }}</b> "

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "magenta"

    [blocks.segments.options]
    branch_icon = " "
    fetch_status = true
    template = "{{ .HEAD }}{{ if gt .Ahead 0 }} <cyan>⇡{{ .Ahead }}</>{{ end }}{{ if gt .Behind 0 }} <yellow>⇣{{ .Behind }}</>{{ end }}{{ if or (gt .Added 0) (gt .Deleted 0) }} ({{ if gt .Added 0 }}<green>+{{ .Added }}</>{{ end }}{{ if and (gt .Added 0) (gt .Deleted 0) }},{{ end }}{{ if gt .Deleted 0 }}<red>-{{ .Deleted }}</>{{ end }}){{ end }}{{ if .Working.Changed }} <yellow>*</>{{ end }}{{ if .Staging.Changed }} <cyan>+</>{{ end }}{{ if .Rebase }} <red>[rebasing]</>{{ end }}{{ if .CherryPick }} <red>[cherry-pick]</>{{ end }}{{ if .Merge }} <red>[merging]</>{{ end }}"

  [[blocks.segments]]
  type = "dotnet"
  style = "plain"
  template = " .NET {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }} "
  foreground = "yellow"

  [[blocks.segments]]
  type = "kotlin"
  style = "plain"
  template = "  {{ .Full }} "
  foreground = "yellow"

  [[blocks.segments]]
  type = "node"
  style = "plain"
  template = "  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
  foreground = "yellow"

  [[blocks.segments]]
  type = "python"
  style = "plain"
  template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "
  foreground = "yellow"

  [[blocks.segments]]
  type = "rust"
  style = "plain"
  template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
  foreground = "yellow"

  [[blocks.segments]]
  type = "bun"
  style = "plain"
  template = "  {{ .Full }} "
  foreground = "yellow"

  [[blocks.segments]]
  type = "npm"
  style = "plain"
  template = "  {{ .Full }} "
  foreground = "yellow"

  [[blocks.segments]]
  type = "react"
  style = "plain"
  template = "  {{ .Full }} "
  foreground = "yellow"

  [[blocks.segments]]
  type = "docker"
  style = "plain"
  template = "  {{ .Context }} "
  foreground = "yellow"

[[blocks]]
type = "prompt"
alignment = "right"
newline = false

  [[blocks.segments]]
  type = "time"
  style = "plain"
  foreground = "white"

    [blocks.segments.options]
    time_format = "15:04:05"
    template = "<b>{{ .CurrentDate | date .Format }}</b>"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  template = "╰─ "
  foreground = "gray"

  [[blocks.segments]]
  type = "session"
  style = "plain"
  foreground = "green"
  template = "<b>{{ .UserName }}@{{ .HostName }}</b>"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "gray"
  foreground_templates = [ "{{ if gt .Code 0 }}red{{ end }}" ]
  template = " ❯"

[[blocks]]
type = "rprompt"
alignment = "right"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  template = '{{ if .Env.SPOTIFY_NOW_PLAYING }}{{ .Env.SPOTIFY_NOW_PLAYING }}{{ end }}'
  foreground = "green"
